// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeb9NkiOXItrIY0WLwppWfJqKbT9HvnjM',
    appId: '1:715902501201:web:97fd2e1aab01e813711370',
    messagingSenderId: '715902501201',
    projectId: 'scholarsphere-d44f5',
    authDomain: 'scholarsphere-d44f5.firebaseapp.com',
    storageBucket: 'scholarsphere-d44f5.firebasestorage.app',
    measurementId: 'G-3YTN0SWF1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvmRuytsZBumzhUR0D4SBjUxjCrXjUI4M',
    appId: '1:715902501201:android:4621ce594064ece6711370',
    messagingSenderId: '715902501201',
    projectId: 'scholarsphere-d44f5',
    storageBucket: 'scholarsphere-d44f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrgJXF_onQya4fvdOTrIw4SFdp4RcGvuA',
    appId: '1:715902501201:ios:da78114a6092a2d3711370',
    messagingSenderId: '715902501201',
    projectId: 'scholarsphere-d44f5',
    storageBucket: 'scholarsphere-d44f5.firebasestorage.app',
    iosClientId: '715902501201-33n6grmt1d48ljsp434osaasolo05dku.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarsphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrgJXF_onQya4fvdOTrIw4SFdp4RcGvuA',
    appId: '1:715902501201:ios:da78114a6092a2d3711370',
    messagingSenderId: '715902501201',
    projectId: 'scholarsphere-d44f5',
    storageBucket: 'scholarsphere-d44f5.firebasestorage.app',
    iosClientId: '715902501201-33n6grmt1d48ljsp434osaasolo05dku.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarsphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeb9NkiOXItrIY0WLwppWfJqKbT9HvnjM',
    appId: '1:715902501201:web:2437637b64405c3a711370',
    messagingSenderId: '715902501201',
    projectId: 'scholarsphere-d44f5',
    authDomain: 'scholarsphere-d44f5.firebaseapp.com',
    storageBucket: 'scholarsphere-d44f5.firebasestorage.app',
    measurementId: 'G-EGXXRMY2JR',
  );
}
